version: '3'

services:
  mongodb:
    image: mongo:latest
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /opt/data/mongo_home:/data/db
    restart: always

  backend:
    image: realize:2.0.2
    hostname: backend
    ports:
      - "8080:8080"
      - "8082:8082" 
      - "443:443"
    environment:
      - GO111MODULE=on

      - HTTP_READ_TIMEOUT=${HTTP_READ_TIMEOUT}
      - HTTP_WRITE_TIMEOUT=${HTTP_WRITE_TIMEOUT}
      - HTTP_READ_HEADER_TIMEOUT=${HTTP_READ_HEADER_TIMEOUT}
      - HTTP_SHUTDOWN_TIMEOUT=${HTTP_SHUTDOWN_TIMEOUT}
      - PORT=${PORT}
      - HTTP_HOST=${HTTP_HOST}
      - HTTP_ALLOWED_ORIGINS=${HTTP_ALLOWED_ORIGINS}
      - HTTP_PORT=${HTTP_PORT}

      # DB
      - MONGODB_ADDRS=${MONGODB_ADDRS}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_TIMEOUT=${MONGODB_TIMEOUT}


    volumes:
      - ../../.realize.yaml:/go/src/github.com/anomotor/.realize.yaml
      - ../../main.go:/go/src/github.com/anomotor/main.go
      - ../../go.mod:/go/src/github.com/anomotor/go.mod
      - ../../go.sum:/go/src/github.com/anomotor/go.sum
      - ../../internal:/go/src/github.com/anomotor/internal/
      - ../../configs:/go/src/github.com/anomotor/configs/
    working_dir: /go/src/github.com/anomotor

    entrypoint: [
      "sh",
      "-c",
      "realize start"]
    
    depends_on:
      - mongodb
    restart: always