version: '3'

services:
  mongodb:
    image: mongo:latest
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /opt/data/mongo_home:/data/db
    restart: always

  backend:
    image: "anmotor:${BUILD_VERSION}"
    hostname: anmotor
    ports:
      - "8080:8080"
    environment:
      # HTTP
      - HTTP_READ_TIMEOUT=${HTTP_READ_TIMEOUT}
      - HTTP_WRITE_TIMEOUT=${HTTP_WRITE_TIMEOUT}
      - HTTP_READ_HEADER_TIMEOUT=${HTTP_READ_HEADER_TIMEOUT}
      - HTTP_SHUTDOWN_TIMEOUT=${HTTP_SHUTDOWN_TIMEOUT}
      - HTTP_PORT=${HTTP_PORT}
      - HTTP_HOST=${HTTP_HOST}
      # DB
      - MONGODB_ADDRS=${MONGODB_ADDRS}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_TIMEOUT=${MONGODB_TIMEOUT}
    depends_on:
      - mongodb
    restart: always
